env:
  es6: true
  node: true
extends:
  - airbnb-base
plugins:
  - babel
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: 0,
}
